document.addEventListener("DOMContentLoaded",function(){
 App.init("users","Users & Roles");const c=document.getElementById("pageContent");let rows=[];
 function render(){c.innerHTML=App.pageHeader("Users & Roles","Manage staff accounts and access roles.",`<button class="btn btn-primary" id="add"><i class="bi bi-person-plus me-1"></i>Add User</button>`)+App.filterBar([{type:"search",id:"q",label:"Search users…"} ,{type:"select",id:"s",label:"All Roles",options:["Admin","Store Manager","Pharmacist"]}])+`<div class="msms-card section-card"><div class="card-body p-0" id="t"></div></div>`;draw();q.oninput=draw;s.onchange=draw;add.onclick=form}
 function draw(){let q=(document.getElementById("q")?.value||"").toLowerCase(),s=document.getElementById("s")?.value||"";let f=rows.filter(r=>(!s||r.role===s)&&`${r.name} ${r.email}`.toLowerCase().includes(q));
 t.innerHTML=App.table(f,[{label:"User",render:r=>`${App.avatar(r.name)} <strong class="ms-2">${r.name}</strong>`},{key:"email",label:"Email"},{key:"role",label:"Role"},{key:"status",label:"Status",badge:true},{key:"lastLogin",label:"Last Login"},{label:"Actions",render:r=>App.actionBtn("bi-pencil","edit","Edit")+App.actionBtn(r.status==="Active"?"bi-person-x":"bi-person-check", "toggle","Change status")}],{hover:true});
 document.querySelectorAll(".edit").forEach((b,i)=>b.onclick=()=>form(f[i]));document.querySelectorAll(".toggle").forEach((b,i)=>b.onclick=()=>toggle(f[i]));
 }
 async function toggle(r){await API.updateUser(r.id,{status:r.status==="Active"?"Inactive":"Active"});await load();App.toast({type:"success",title:"User updated",message:`${r.name} is now ${r.status==="Active"?"inactive":"active"}.`})}
 function form(r){r=r||{name:"",email:"",role:"Pharmacist",status:"Active"};document.getElementById("modalRoot").innerHTML=App.modalHtml("userModal",r.id?"Edit User":"Add User",`<form id="f"><div class="row g-3">
 <div class="col-md-6"><label class="form-label">Name *</label><input class="form-control" id="name" value="${r.name}" required></div><div class="col-md-6"><label class="form-label">Email *</label><input type="email" class="form-control" id="email" value="${r.email}" required></div>
 <div class="col-md-6"><label class="form-label">Role</label><select class="form-select" id="role">${["Admin","Store Manager","Pharmacist"].map(x=>`<option ${r.role===x?"selected":""}>${x}</option>`).join("")}</select></div>
 <div class="col-md-6"><label class="form-label">Status</label><select class="form-select" id="status"><option ${r.status==="Active"?"selected":""}>Active</option><option ${r.status==="Inactive"?"selected":""}>Inactive</option></select></div></div></form>`,`<button class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary" id="save">Save</button>`);new bootstrap.Modal(userModal).show();
 save.onclick=async()=>{if(!f.checkValidity()){f.reportValidity();return}let d={name:name.value,email:email.value,role:role.value,status:status.value};await(r?API.updateUser(r.id,d):API.createUser(d));bootstrap.Modal.getInstance(userModal).hide();await load();App.toast({type:"success",title:"Saved",message:"User account saved."})}}
 async function load(){rows=await API.getUsers();render()}load();
});